name: Android CI

# manual only: doesn't work, must be on master branch or something
# on: workflow_dispatch

# on any push to specific branches:
on:
  push:
    branches: [ "tunnelmode" ]
  pull_request:
    branches: [ "tunnelmode" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.4.2
      with:
        ndk-version: r26b
        add-to-path: true

    - name: setup gradle current
      uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        gradle-version: current
        cache-read-only: false

    - name: create apk with gradle
      run: gradle :app:assembleNonRootRelease

